# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# The Task 'PublishBuildArtifacts@1' has been converted to an output named '' in the templateContext section.
parameters:
- name: targetOsArch
  type: string
jobs:
- job: ${{parameters.targetOsArch}}
  steps:
  - checkout: self
    path: 's'
  - template: /azure-pipelines/build/linux/du/templates/doclient-lite-native-steps.yml@self
    parameters:
      targetOsArch: ${{parameters.targetOsArch}}
      config: minsizerel
      skiptests: true
  - task: CopyFiles@2
    inputs:
      SourceFolder: '/tmp/build-deliveryoptimization-agent/linux-minsizerel'
      Contents: |
        *.deb
      TargetFolder: '/tmp/${{parameters.targetOsArch}}'
      CleanTargetFolder: true
    displayName: 'Copy agent .deb file'
  - template: /azure-pipelines/build/linux/du/templates/dosdkcpp-native-steps.yml@self
    parameters:
      targetOsArch: ${{parameters.targetOsArch}}
      config: minsizerel
      skiptests: true
  - task: CopyFiles@2
    inputs:
      SourceFolder: '/tmp/build-deliveryoptimization-sdk/linux-minsizerel'
      Contents: |
        *.deb
      TargetFolder: '/tmp/${{parameters.targetOsArch}}'
      CleanTargetFolder: false
    displayName: 'Copy sdk .deb files'
  - template: /azure-pipelines/build/linux/du/templates/dopapt-native-steps.yml@self
    parameters:
      targetOsArch: ${{parameters.targetOsArch}}
      config: minsizerel
  - task: CopyFiles@2
    inputs:
      SourceFolder: '/tmp/build-deliveryoptimization-plugin-apt/linux-minsizerel'
      Contents: |
        *.deb
      TargetFolder: '/tmp/${{parameters.targetOsArch}}'
      CleanTargetFolder: false
    displayName: 'Copy plugin .deb file'
  - task: DeleteFiles@1
    inputs:
      SourceFolder: $(Build.ArtifactStagingDirectory)
      Contents: |
        **/*
    displayName: 'Clean build folder before creating tar file folder'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: /tmp/${{parameters.targetOsArch}}
      includeRootFolder: False
      archiveType: tar
      archiveFile: $(build.ArtifactStagingDirectory)/${{parameters.targetOsArch}}-packages.tar
    displayName: 'Create .tar file'
  templateContext:
    outputs:
    - output: pipelineArtifact
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'github-release-artifacts'
      publishLocation: 'Container'
    - output: pipelineArtifact
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'deliveryoptimization-agent'
      publishLocation: 'Container'
    - output: pipelineArtifact
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'deliveryoptimization-sdk'
      publishLocation: 'Container'
    - output: pipelineArtifact
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'deliveryoptimization-plugin-apt'
      publishLocation: 'Container'